# site properties and page defaults
title: Bennett Lab 
subtitle: IMPROVING CLINICAL OUTCOMES THROUGH INFORMATICS AND DATA SCIENCE
description: Dr. Bennett’s group focuses on clinical decision-making in high-risk environments such as intensive care units and on the development and implementation of 
informatics and data science methods and tools to improve outcomes.
header: images/banner6.jpg
footer: images/banner6.jpg

# site social media and other links
links:
  email: contact@rebullm.com
  orcid: 0000-0003-1483-4236
  google-scholar: https://scholar.google.com/citations?user=g2HQCpsAAAAJ&hl=en
  github: tdbennett
  twitter: rebullm
  youtube: rebullm

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
